name: Release Drafter

on:
  # for manually running the workflow
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, edited]
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        with:
          config-name: config/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add step summary
        run: |
          echo "# [Draft a release](${{ steps.release-drafter.outputs.html_url }}) ✍️" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## ${{ steps.release-drafter.outputs.name }}" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.release-drafter.outputs.body }}" >> $GITHUB_STEP_SUMMARY
